"""Fleet / cohort analysis + attacker-profile classification tests."""

import json
from pathlib import Path

import pytest

from rootsentry.catalog import Platform
from rootsentry.engine import Evidence, Posture, evaluate
from rootsentry.fleet import (
    Profile, PROFILES, classify_profiles, analyze_fleet, FleetReport,
    DeviceResult,
)

EXAMPLE = Path(__file__).resolve().parent.parent / "examples" / "fleet.android.json"


# --------------------------------------------------------------------------- #
# profiles
# --------------------------------------------------------------------------- #

def _classify(**kw):
    return classify_profiles(evaluate(Evidence(platform=kw.pop("platform", Platform.ANDROID), **kw)))


def test_profiles_have_unique_ids():
    ids = [p.id for p in PROFILES]
    assert len(ids) == len(set(ids))


@pytest.mark.parametrize("p", PROFILES, ids=[p.id for p in PROFILES])
def test_profile_wellformed(p):
    assert p.severity in {"info", "elevated", "high", "critical"}
    assert p.requires_any
    assert all(isinstance(g, tuple) and g for g in p.requires_any)
    assert p.label and p.description


def test_clean_device_no_profiles():
    assert _classify(system_props={"ro.build.tags": "release-keys"}) == []


def test_dynamic_instrumentation_profile():
    hits = _classify(open_ports=[27042])
    assert any(p.id == "dynamic_instrumentation" for p in hits)


def test_rooted_and_hooked_requires_both_groups():
    only_root = _classify(present_files=["/system/xbin/su"])
    assert not any(p.id == "rooted_and_hooked" for p in only_root)
    both = _classify(present_files=["/system/xbin/su", "/data/local/tmp/frida-server"])
    assert any(p.id == "rooted_and_hooked" for p in both)


def test_emulator_farm_profile():
    hits = _classify(system_props={"ro.hardware": "goldfish"})
    assert any(p.id == "emulator_farm" for p in hits)


def test_repackaged_profile():
    hits = _classify(runtime_flags=["signature_mismatch"])
    assert any(p.id == "repackaged_app" for p in hits)


def test_evasive_root_profile():
    hits = _classify(installed_packages=["io.github.huskydg.magisk"],
                     system_props={"ro.boot.selinux": "permissive"})
    assert any(p.id == "evasive_root" for p in hits)


def test_mitm_profile_needs_both_groups():
    # user CA alone (no elevated access) should not raise mitm_analysis
    weak = _classify(runtime_flags=["user_ca_installed"])
    assert not any(p.id == "mitm_analysis" for p in weak)
    strong = _classify(present_files=["/system/xbin/su"],
                       runtime_flags=["user_ca_installed", "system_proxy_active"])
    assert any(p.id == "mitm_analysis" for p in strong)


def test_profiles_sorted_severity_first():
    hits = _classify(present_files=["/system/xbin/su", "/data/local/tmp/frida-server"],
                     installed_packages=["com.topjohnwu.magisk"], open_ports=[27042])
    order = {"critical": 0, "high": 1, "elevated": 2, "info": 3}
    sev = [order[p.severity] for p in hits]
    assert sev == sorted(sev)


def test_profile_matches_helper_and_or_semantics():
    p = Profile("x", "x", "high",
                (("a", "b"), ("c",)), "desc")
    assert p.matches({"a", "c"})
    assert p.matches({"b", "c"})
    assert not p.matches({"a"})          # missing group 2
    assert not p.matches({"c"})          # missing group 1
    assert not p.matches(set())


# --------------------------------------------------------------------------- #
# fleet analysis
# --------------------------------------------------------------------------- #

def _load():
    data = json.loads(EXAMPLE.read_text(encoding="utf-8"))
    return data["devices"]


def test_example_fixture_loads():
    snaps = _load()
    assert len(snaps) >= 10


def test_analyze_empty_fleet():
    r = analyze_fleet([])
    assert r.total == 0
    assert r.compromised_rate == 0.0
    assert r.cooccurrence == []
    assert r.outliers == []


def test_analyze_returns_report():
    r = analyze_fleet(_load())
    assert isinstance(r, FleetReport)
    assert r.total == len(_load())


def test_posture_counts_sum_to_total():
    r = analyze_fleet(_load())
    assert sum(r.posture_counts.values()) == r.total


def test_clean_devices_counted_trusted():
    r = analyze_fleet(_load())
    assert r.posture_counts["TRUSTED"] >= 3


def test_compromised_rate_between_0_and_1():
    r = analyze_fleet(_load())
    assert 0.0 <= r.compromised_rate <= 1.0
    # this fixture is mostly bad devices
    assert r.compromised_rate > 0.5


def test_device_ids_preserved():
    r = analyze_fleet(_load())
    ids = {d.device_id for d in r.devices}
    assert "clean-01" in ids
    assert "instr-01" in ids


def test_device_id_autogenerated_when_missing():
    r = analyze_fleet([{"platform": "android"}, {"platform": "android"}])
    ids = [d.device_id for d in r.devices]
    assert ids == ["device-0", "device-1"]


def test_id_alias_accepted():
    r = analyze_fleet([{"id": "alias-1", "platform": "android"}])
    assert r.devices[0].device_id == "alias-1"


def test_signal_counts_aggregate():
    r = analyze_fleet(_load())
    assert r.signal_counts.get("android.magisk.pkg", 0) >= 2


def test_category_counts_present():
    r = analyze_fleet(_load())
    assert r.category_counts.get("root", 0) >= 1
    assert r.category_counts.get("hook", 0) >= 1


def test_technique_counts_present():
    r = analyze_fleet(_load())
    assert r.technique_counts.get("T1404", 0) >= 1


def test_profile_counts_present():
    r = analyze_fleet(_load())
    assert r.profile_counts.get("emulator_farm", 0) >= 3
    assert r.profile_counts.get("dynamic_instrumentation", 0) >= 1


def test_cooccurrence_has_lift():
    r = analyze_fleet(_load())
    assert r.cooccurrence
    for a, b, c, lift in r.cooccurrence:
        assert a < b           # canonical order
        assert c >= 2          # default min_count
        assert lift > 0


def test_cooccurrence_respects_min_count():
    snaps = _load()
    r = analyze_fleet(snaps, cooccurrence_min_count=3)
    assert all(c >= 3 for (_a, _b, c, _l) in r.cooccurrence)


def test_cooccurrence_lift_above_one_for_toolkit():
    # frida lib + magisk appear together in instr devices -> lift > 1
    r = analyze_fleet(_load())
    pairs = {(a, b): lift for (a, b, c, lift) in r.cooccurrence}
    # emulator props strongly co-occur
    found = [lift for (a, b), lift in pairs.items()
             if "emu" in a and "emu" in b]
    assert found and max(found) > 1.0


def test_outliers_have_min_signals():
    r = analyze_fleet(_load(), outlier_min_signals=4)
    assert all(n >= 4 for (_d, _s, n) in r.outliers)


def test_outliers_sorted_by_signal_count_desc():
    r = analyze_fleet(_load())
    counts = [n for (_d, _s, n) in r.outliers]
    assert counts == sorted(counts, reverse=True)


def test_to_dict_shape():
    r = analyze_fleet(_load())
    d = r.to_dict()
    assert set(d) >= {
        "total", "compromised_rate", "posture_counts", "category_counts",
        "technique_counts", "profile_counts", "top_signals", "cooccurrence",
        "outliers",
    }
    assert "devices" not in d


def test_to_dict_include_devices():
    r = analyze_fleet(_load())
    d = r.to_dict(include_devices=True)
    assert "devices" in d
    assert len(d["devices"]) == r.total
    sample = d["devices"][0]
    assert {"device_id", "posture", "score", "profiles", "fired"} <= set(sample)


def test_to_dict_json_serializable():
    r = analyze_fleet(_load())
    json.dumps(r.to_dict(include_devices=True))  # must not raise


def test_top_signals_capped_and_sorted():
    r = analyze_fleet(_load())
    top = r.to_dict()["top_signals"]
    assert len(top) <= 20
    counts = [t["count"] for t in top]
    assert counts == sorted(counts, reverse=True)


def test_technique_counts_in_dict_have_names():
    r = analyze_fleet(_load())
    for t in r.to_dict()["technique_counts"]:
        assert t["id"]
        assert "name" in t


def test_device_result_dataclass():
    r = analyze_fleet([{"device_id": "z", "platform": "android",
                        "present_files": ["/system/xbin/su"]}])
    dr = r.devices[0]
    assert isinstance(dr, DeviceResult)
    assert dr.device_id == "z"
    assert dr.verdict.posture == Posture.COMPROMISED


def test_single_clean_device_zero_compromise():
    r = analyze_fleet([{"platform": "android",
                        "system_props": {"ro.build.tags": "release-keys"}}])
    assert r.compromised_rate == 0.0
    assert r.cooccurrence == []
